export const popupImg = document.querySelector('.card-img'); /* -блок формы редктирования картинки*/
export const cardTemplate = document.querySelector('#card-template').content;
export const formCard = document.forms.popupCard; /*форма карточки*/
export const inputCardName = formCard.elements.name;
export const inputCardSubtitle = formCard.elements.subtitle;
export const cards = document.querySelector('.cards'); /*карточки*/
export const popupCard = document.querySelector('.popup__card'); /*блок формы редктирования профиля*/
export const popupProfile = document.querySelector('.popup__profile');/* _блок формы редктирования карточки*/
export const profileName = document.querySelector('.profile__title');/*имя профиля*/
export const profileDescription = document.querySelector('.profile__subtitle');/*описание профиля*/
export const formProfile = document.forms.popupProfile;
export const inputProfileName = formProfile.elements.name;
export const inputProfileSubtitle = formProfile.elements.subtitle;
export const popups = document.querySelectorAll('.popup');
export const popupProfileButtonEdit = document.querySelector('.profile__edit-button'); /* _кнопка редкатирования профиля*/
export const popupCardButtonAdd = document.querySelector('.profile__add-button'); /*кнопка добавить попап карточки*/
export const profileIcon = document.querySelector('.profile__avatar');
export const popupProfileIcon = document.querySelector('.popup__profile-icon');
export const formProfileIcon = document.forms.popupProfileIcon;
